/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FortuneReactiveHandlerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "fortuneContract"
      | "getReactionStats"
      | "onEvent"
      | "reactionCount"
      | "supportsInterface"
      | "walletReactions"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "FortuneReaction" | "LiveFeedUpdate"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "fortuneContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReactionStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onEvent",
    values: [AddressLike, BytesLike[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reactionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "walletReactions",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "fortuneContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReactionStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "onEvent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reactionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "walletReactions",
    data: BytesLike
  ): Result;
}

export namespace FortuneReactionEvent {
  export type InputTuple = [
    wallet: AddressLike,
    tokenId: BigNumberish,
    rarity: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    wallet: string,
    tokenId: bigint,
    rarity: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    wallet: string;
    tokenId: bigint;
    rarity: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiveFeedUpdateEvent {
  export type InputTuple = [
    reactionCount: BigNumberish,
    latestWallet: AddressLike
  ];
  export type OutputTuple = [reactionCount: bigint, latestWallet: string];
  export interface OutputObject {
    reactionCount: bigint;
    latestWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FortuneReactiveHandler extends BaseContract {
  connect(runner?: ContractRunner | null): FortuneReactiveHandler;
  waitForDeployment(): Promise<this>;

  interface: FortuneReactiveHandlerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  fortuneContract: TypedContractMethod<[], [string], "view">;

  getReactionStats: TypedContractMethod<
    [wallet: AddressLike],
    [[bigint, bigint]],
    "view"
  >;

  onEvent: TypedContractMethod<
    [emitter: AddressLike, eventTopics: BytesLike[], data: BytesLike],
    [void],
    "nonpayable"
  >;

  reactionCount: TypedContractMethod<[], [bigint], "view">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  walletReactions: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "fortuneContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getReactionStats"
  ): TypedContractMethod<[wallet: AddressLike], [[bigint, bigint]], "view">;
  getFunction(
    nameOrSignature: "onEvent"
  ): TypedContractMethod<
    [emitter: AddressLike, eventTopics: BytesLike[], data: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reactionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "walletReactions"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getEvent(
    key: "FortuneReaction"
  ): TypedContractEvent<
    FortuneReactionEvent.InputTuple,
    FortuneReactionEvent.OutputTuple,
    FortuneReactionEvent.OutputObject
  >;
  getEvent(
    key: "LiveFeedUpdate"
  ): TypedContractEvent<
    LiveFeedUpdateEvent.InputTuple,
    LiveFeedUpdateEvent.OutputTuple,
    LiveFeedUpdateEvent.OutputObject
  >;

  filters: {
    "FortuneReaction(address,uint256,string,uint256)": TypedContractEvent<
      FortuneReactionEvent.InputTuple,
      FortuneReactionEvent.OutputTuple,
      FortuneReactionEvent.OutputObject
    >;
    FortuneReaction: TypedContractEvent<
      FortuneReactionEvent.InputTuple,
      FortuneReactionEvent.OutputTuple,
      FortuneReactionEvent.OutputObject
    >;

    "LiveFeedUpdate(uint256,address)": TypedContractEvent<
      LiveFeedUpdateEvent.InputTuple,
      LiveFeedUpdateEvent.OutputTuple,
      LiveFeedUpdateEvent.OutputObject
    >;
    LiveFeedUpdate: TypedContractEvent<
      LiveFeedUpdateEvent.InputTuple,
      LiveFeedUpdateEvent.OutputTuple,
      LiveFeedUpdateEvent.OutputObject
    >;
  };
}
