/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FortuneReactiveHandler } from "./FortuneReactiveHandler";
export type { SomniaWhisperFortune } from "./SomniaWhisperFortune";
